### ISSUE TITLE
Incompatible SmoothingGroupNumber handling

### ISSUE THREAD

**Issue by nesc58** [JeremyAnsel/JeremyAnsel.Media.WavefrontObj#12]
Hi,
I have received an obj file which contains a smoothing group number which is out of range of an integer.
I have not found any special definition of the smoothing group number. Is it possible to change it e.g. to a simple string or long?

To write the same smoothing value after reading a file it is may necessary to know the original value (0 or off). Technically it is no difference but the checksum of the file would change. For me it is no error when the term off is changed to 0.

Is there a way to solve the integer out of range error without breaking too much?

Thanks

**Comment by JeremyAnsel** [comment]
Hello,
I've changed the type of the `SmoothingGroupNumber` member from `int` to `long`.

**Comment by nesc58** [comment]
Works like a charm. Thank you
