### ISSUE TITLE
Adding comments?

### ISSUE THREAD

**Issue by AdamSzofran** [JeremyAnsel/JeremyAnsel.Media.WavefrontObj#2]
Is there a way to insert custom comments into the obj file during output? I'd like to add some comments at the top of the files I'm creating. Thanks.

**Comment by JeremyAnsel** [comment]
Hello,
In 76780c8b0aaf6d2ab07d424d217a6d0c16d2d60c, I've added a `HeaderText` property to `ObjFile` and `ObjMaterialFile`. With this property, you can read or write comments to the top of the files. Does it fill your needs?

**Comment by AdamSzofran** [comment]
Looks like it might. I'll give it a try. Thanks!

**Comment by AdamSzofran** [comment]
Works great! Thank you Jeremy!
