### ISSUE TITLE
A usemtl statement has too many values

### ISSUE THREAD

**Issue by MGerdel** [JeremyAnsel/JeremyAnsel.Media.WavefrontObj#3]
Whitespaces in the material name cause an exception when calling `ObjFile.FromFile(filePath);`

For example:
`usemtl name with whitespaces`

Other 3D tools like blender or threejs are allowing whitespaces in the material name.

Would it be possible to allow whitespaces in this library too?

**Comment by JeremyAnsel** [comment]
Hello,
I've updated the library.
Now whitespaces are allowed in material name.
In 40020b8df9eb953f1fa2380411ab5efea4562758, I've updated the `newmtl` and `usemtl` statements to allow whitespaces.

**Comment by MGerdel** [comment]
@JeremyAnsel Would it be possible to release this fix for a "2.20" version or target net standard 2.0 again?

**Comment by JeremyAnsel** [comment]
Hello,
I've added support for net standard 2.0
