### ISSUE TITLE
Material with whitespaces cannot be read by ObjFileReader.FromStream

### ISSUE THREAD

**Issue by MGerdel** [JeremyAnsel/JeremyAnsel.Media.WavefrontObj#6]
https://github.com/JeremyAnsel/JeremyAnsel.Media.WavefrontObj/blob/7b83ffbde616f021e6f1b3821097799d7f7da7e4/JeremyAnsel.Media.WavefrontObj/JeremyAnsel.Media.WavefrontObj/ObjFileReader.cs#L784

If an obj with "mtllib my cool material.mtl" is read, an exception is beeing thrown that the file has no extension.

Could this be fixed accordingly to https://github.com/JeremyAnsel/JeremyAnsel.Media.WavefrontObj/issues/3?

**Comment by JeremyAnsel** [comment]
Hello,
I've modified the code to allow spaces in the `mtllib` instruction.
