### ISSUE TITLE
Whitespace inside .mtl

### ISSUE THREAD

**Issue by rudcode** [JeremyAnsel/JeremyAnsel.Media.WavefrontObj#7]
Hi, I have this .mtl file that have something like this

```
map_Bump Amaranth Seed_N.png
map_Kd Amaranth Seed_D.png
```

and I got this error
```
A filename must have an extension.
```

I think the error came from [this line](https://github.com/JeremyAnsel/JeremyAnsel.Media.WavefrontObj/blob/master/JeremyAnsel.Media.WavefrontObj/JeremyAnsel.Media.WavefrontObj/ObjMaterialFileReader.cs#L776) but I have no idea how to fix it properly, thank you.

**Comment by JeremyAnsel** [comment]
Hello,
To define a new material you have to use the `newmtl` statement.
```
newmtl Amaranth
map_Bump Seed_N.png
map_Kd Seed_D.png
```

**Comment by rudcode** [comment]
Sorry, I think my explanation is not complete.

I have this file
```
"D:\3d\obj\Amaranth Seed.mtl"
"D:\3d\obj\Amaranth Seed.obj"
"D:\3d\obj\Amaranth Seed_D.png"
"D:\3d\obj\Amaranth Seed_N.png"
```

this is the content of "Amaranth seed.mtl"
```
newmtl Amaranth_Seed
Ns 0.000000
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.000000 0.000000 0.000000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 1
map_Bump Amaranth Seed_N.png
map_Kd Amaranth Seed_D.png
```

The problem is if you have whitespace in texture filename.

**Comment by JeremyAnsel** [comment]
Hello,
Thanks for the explain. I understand now.
Your PR seems good. I've merged it.
